MYSQL-MASTER:
  image: 172.16.1.81:5000/mysql-master:v5.7.2
  hostname: mysql
  ports:
  - '3306:3306'
  environment:
    REPLICATION_MASTER: 'true'
    MYSQL_PASS: "ab888888"
  volumes:
    - /var/lib/mysql-master:/var/lib/mysql
        
MYSQL-SLAVE:
  image: 172.16.1.81:5000/mysql-master:v5.7.2
  links:
  - MYSQL-MASTER:mysql
  environment:
    REPLICATION_SLAVE: 'true'
    MYSQL_PASS: "ab888888"
  volumes:
    - /var/lib/mysql-slave:/var/lib/mysql