MYSQL-MASTER:
  image: 172.16.1.81:5000/mysql5.5
  hostname: mysql
  ports:
  - '3306:3306'
  environment:
    REPLICATION_MASTER: 'true'
    MYSQL_PASS: "ab888888"
        
MYSQL-SLAVE:
  image: 172.16.1.81:5000/mysql5.5
  links:
  - MYSQL-MASTER:mysql
  environment:
    REPLICATION_SLAVE: 'true'
