MYSQL-MASTER:
  image: 172.16.1.81:5000/mysql-master:v5.7.3
  hostname: mysql
  labels:
    io.rancher.scheduler.affinity:host_label: foo=mysql-master
  ports:
  - '3306:3306'
  environment:
    REPLICATION_MASTER: 'true'
    MYSQL_PASS: "ab888888"
  volumes:
    - /var/lib/mysql-master:/var/lib/mysql
    - /var/lib/mysqlRepSet/:/var/lib/mysqlRepSet/
        
MYSQL-SLAVE:
  image: 172.16.1.81:5000/mysql-master:v5.7.3
  labels:
    io.rancher.scheduler.affinity:host_label: foo=mysql-slave
  links:
  - MYSQL-MASTER:mysql
  environment:
    REPLICATION_SLAVE: 'true'
    MYSQL_PASS: "ab888888"
  volumes:
    - /var/lib/mysql-slave:/var/lib/mysql
    - /var/lib/mysqlRepSet/:/var/lib/mysqlRepSet/