.catalog:
    name: "mysql-master"
    version: "v0.2.0"
    description: "mysql-master"
    questions:
     - variable: "MASTER_IP"
       description: "IP or hostname of the NFS Server" 
       label: "MASTER_IP"
       required: false
       type: "host"
     - variable: "SLAVE_IP"
       description: "IP or hostname of the NFS Server"
       label: "SLAVE_IP"
       required: false
       type: "string"
    
MYSQL-MASTER:
  scale: 1
  
MYSQL-SLAVE:
  scale: 1